/*
 * File: wgl_ext_api.c
 * Purpose: Wrapper functions for Win32 OpenGL wgl extension functions
 *
 * Authors: Jon TURNEY
 *
 * Copyright (c) Jon TURNEY 2009
 *
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE ABOVE LISTED COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifdef HAVE_XWIN_CONFIG_H
#include <xwin-config.h>
#endif

#include <X11/Xwindows.h>
#include <GL/gl.h>
#include <GL/glext.h>
#include <glx/glxserver.h>
#include <glx/glxext.h>
#include <wgl_ext_api.h>

#define RESOLVE_DECL(type, symbol) \
    static type type##proc = NULL;

#define PRERESOLVE(type, symbol) \
    type##proc = (type)wglGetProcAddress(symbol); \
    if (type##proc == NULL) \
        ErrorF("wglwrap: Can't resolve \"%s\"\n", symbol); \
    else \
        ErrorF("wglwrap: Resolved \"%s\"\n", symbol);

#define RESOLVE_RET(type, symbol, retval) \
  if (type##proc == NULL) { \
  __glXErrorCallBack(0); \
  return retval; \
      }

#define RESOLVE(procname, symbol) RESOLVE_RET(procname, symbol,)

#define RESOLVED_PROC(type) type##proc

/*
 * There are extensions to the wgl*() API as well; again we call
 * these functions by using wglGetProcAddress() to get a pointer
 * to the function, and wrapping it for cdecl/stdcall conversion
 *
 * This should be autogenerated as well, really...
 *
 * We arrange to resolve the functions up front, as they need a
 * context to work, as we like to use them to be able to select
 * a context.  Again, this assumption fails badly on multimontor
 * systems...
 */

typedef char *(__stdcall *PFNWGLGETEXTENSIONSSTRINGARB)(HDC hdc);
typedef wBOOL (__stdcall *PFNWGLMAKECONTEXTCURRENTARB)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
typedef HDC (__stdcall *PFNWGLGETCURRENTREADDCARB)(VOID);
typedef wBOOL (__stdcall *PFNWGLGETPIXELFORMATATTRIBIVARB)(HDC hdc,
                                                           int iPixelFormat,
                                                           int iLayerPlane,
                                                           UINT nAttributes,
                                                           const int *piAttributes,
                                                           int *piValues);
typedef wBOOL (__stdcall *PFNWGLGETPIXELFORMATATTRIBFVARB)(HDC hdc,
                                                           int iPixelFormat,
                                                           int iLayerPlane,
                                                           UINT nAttributes,
                                                           const int *piAttributes,
                                                           FLOAT *pfValues);
typedef wBOOL (__stdcall *PFNWGLCHOOSEPIXELFORMATARB)(HDC hdc,
                                                     const int *piAttribIList,
                                                     const FLOAT *pfAttribFList,
                                                     UINT nMaxFormats,
                                                     int *piFormats,
                                                     UINT *nNumFormats);

RESOLVE_DECL(PFNWGLGETEXTENSIONSSTRINGARB, "wglGetExtensionsStringARB");
RESOLVE_DECL(PFNWGLMAKECONTEXTCURRENTARB, "wglMakeContextCurrentARB");
RESOLVE_DECL(PFNWGLGETCURRENTREADDCARB, "wglGetCurrentReadDCARB");
RESOLVE_DECL(PFNWGLGETPIXELFORMATATTRIBIVARB, "wglGetPixelFormatAttribivARB");
RESOLVE_DECL(PFNWGLGETPIXELFORMATATTRIBFVARB, "wglGetPixelFormatAttribfvARB");
RESOLVE_DECL(PFNWGLCHOOSEPIXELFORMATARB, "wglChoosePixelFormatARB");

void
wglResolveExtensionProcs(void)
{
  PRERESOLVE(PFNWGLGETEXTENSIONSSTRINGARB, "wglGetExtensionsStringARB");
  PRERESOLVE(PFNWGLMAKECONTEXTCURRENTARB, "wglMakeContextCurrentARB");
  PRERESOLVE(PFNWGLGETCURRENTREADDCARB, "wglGetCurrentReadDCARB");
  PRERESOLVE(PFNWGLGETPIXELFORMATATTRIBIVARB, "wglGetPixelFormatAttribivARB");
  PRERESOLVE(PFNWGLGETPIXELFORMATATTRIBFVARB, "wglGetPixelFormatAttribfvARB");
  PRERESOLVE(PFNWGLCHOOSEPIXELFORMATARB, "wglChoosePixelFormatARB");
}

// WGL_ARB_extensions_string

const char *wglGetExtensionsStringARBWrapper(HDC hdc)
{
  RESOLVE_RET(PFNWGLGETEXTENSIONSSTRINGARB, "wglGetExtensionsStringARB", "");
  return RESOLVED_PROC(PFNWGLGETEXTENSIONSSTRINGARB)(hdc);
}

// WGL_ARB_make_current_read

wBOOL wglMakeContextCurrentARBWrapper(HDC hDrawDC, HDC hReadDC, HGLRC hglrc)
{
  RESOLVE_RET(PFNWGLMAKECONTEXTCURRENTARB, "wglMakeContextCurrentARB", FALSE);
  return RESOLVED_PROC(PFNWGLMAKECONTEXTCURRENTARB)(hDrawDC, hReadDC, hglrc);
}

HDC wglGetCurrentReadDCARBWrapper(VOID)
{
  RESOLVE_RET(PFNWGLGETCURRENTREADDCARB, "wglGetCurrentReadDCARB", NULL);
  return RESOLVED_PROC(PFNWGLGETCURRENTREADDCARB)();
}

// WGL_ARB_pixel_format

wBOOL wglGetPixelFormatAttribivARBWrapper(HDC hdc,
                                          int iPixelFormat,
                                          int iLayerPlane,
                                          UINT nAttributes,
                                          const int *piAttributes,
                                          int *piValues)
{
  RESOLVE_RET(PFNWGLGETPIXELFORMATATTRIBIVARB, "wglGetPixelFormatAttribivARB", FALSE);
  return RESOLVED_PROC(PFNWGLGETPIXELFORMATATTRIBIVARB)(hdc, iPixelFormat, iLayerPlane, nAttributes, piAttributes, piValues);
}

wBOOL wglGetPixelFormatAttribfvARBWrapper(HDC hdc,
                                          int iPixelFormat,
                                          int iLayerPlane,
                                          UINT nAttributes,
                                          const int *piAttributes,
                                          FLOAT *pfValues)
{
  RESOLVE_RET(PFNWGLGETPIXELFORMATATTRIBFVARB, "wglGetPixelFormatAttribfvARB", FALSE);
  return RESOLVED_PROC(PFNWGLGETPIXELFORMATATTRIBFVARB)(hdc, iPixelFormat, iLayerPlane, nAttributes, piAttributes, pfValues);
}

wBOOL wglChoosePixelFormatARBWrapper(HDC hdc,
                                    const int *piAttribIList,
                                    const FLOAT *pfAttribFList,
                                    UINT nMaxFormats,
                                    int *piFormats,
                                    UINT *nNumFormats)
{
  RESOLVE_RET(PFNWGLCHOOSEPIXELFORMATARB, "wglChoosePixelFormatARB", FALSE);
  return RESOLVED_PROC(PFNWGLCHOOSEPIXELFORMATARB)(hdc, piAttribIList, pfAttribFList, nMaxFormats, piFormats, nNumFormats);
}

