branches:
  except:
    - /travis.*/
version: '{build}'
skip_tags: true
clone_depth: 8
environment:
  CYGWIN_MIRROR: http://cygwin.mirror.constant.com
  CACHE: C:\cache
  matrix:
  - BUILD: i686-pc-cygwin
  - BUILD: x86_64-pc-cygwin
install:
- if "%BUILD%"=="x86_64-pc-cygwin" set SETUP=setup-x86_64.exe && set CYGWIN_ROOT=C:\cygwin64
- if "%BUILD%"=="i686-pc-cygwin" set SETUP=setup-x86.exe && set CYGWIN_ROOT=C:\cygwin
- curl -fsSL https://gist.githubusercontent.com/jon-turney/0338af595313f598bfab15a0ac0df847/raw/bd0eeca6be899e7846aa988fbcf15e4e12f5f842/zp_libtool_cleanlafiles.sh -o %CYGWIN_ROOT%\etc\postinstall\zp_libtool_cleanlafiles.sh
- echo Updating Cygwin and installing build prerequisites
- "%CYGWIN_ROOT%\\%SETUP% -qnNdO -R %CYGWIN_ROOT% -s %CYGWIN_MIRROR% -l %CACHE% -g -P \
binutils,\
bison,\
flex,\
gcc-core,\
meson,\
ninja,\
pkg-config,\
python3,\
tar,\
xz,\
windowsdriproto,\
xorgproto,\
libdmx-devel,\
libepoxy-devel,\
libfontenc-devel,\
libfreetype-devel,\
libGL-devel,\
libnettle-devel,\
libpixman1-devel,\
libtirpc-devel,\
libX11-devel,\
libXRes-devel,\
libXau-devel,\
libXaw-devel,\
libXdmcp-devel,\
libXext-devel,\
libXfont2-devel,\
libXi-devel,\
libXinerama-devel,\
libXmu-devel,\
libXpm-devel,\
libXrender-devel,\
libXtst-devel,\
libxcb-ewmh-devel,\
libxcb-icccm-devel,\
libxcb-image-devel,\
libxcb-keysyms-devel,\
libxcb-randr-devel,\
libxcb-render-devel,\
libxcb-render-util-devel,\
libxcb-shape-devel,\
libxcb-util-devel,\
libxcb-xkb-devel,\
libxkbfile-devel,\
zlib-devel,\
font-util,\
khronos-opengl-registry,\
python3-lxml,\
xtrans,\
xkbcomp,\
xkeyboard-config,\
python2-mako,\
python2-six"
- echo Install done
cache:
- C:\cache
build_script:
- SET ORIG_PATH=%PATH%
- SET PATH=%CYGWIN_ROOT%/bin
- '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./test/scripts/build-appveyor.sh"'
artifacts:
- path: staging
deploy: off
test: off
# publish log artifacts on success or failure
on_finish:
- tar -Jcf meson-log.tar.xz build/meson-logs
- tar -Jcf xvfb-piglit.tar.xz build/test/piglit-results/xvfb
- SET PATH=%ORIG_PATH%
- appveyor PushArtifact meson-log.tar.xz
- appveyor PushArtifact xvfb-piglit.tar.xz
